name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger other workflow
        run: |
          echo "Triggering another workflowss manual"
          # Replace with the command to trigger your desired workflow
        env:
          TARGET_BRANCH: ${{ github.event.inputs.branch }}
