name: JMeter Test

on:
  push:
    branches:
      - main

jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run JMeter Tests
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: ./CSVSample.jmx
