TestPlan:
  - Test Plan:
      - Thread Group:
          - HTTP Request Defaults:
              - Base URL: https://your-angular-app.com
          - HTTP Cookie Manager
          - Recording Controller:
              - HTTP(S) Test Script Recorder:
                  - Port: 8888
                  - Capture HTTP Headers: true
                  - Capture HTTP Headers: true
          - View Results Tree
      - Thread Group:
          - Number of Threads (Users): 10
          - Ramp-Up Period (in seconds): 5
          - Loop Count: 2
          - HTTP Request:
              - Method: GET
              - Path: /path/to/your/page
          - View Results Tree
