name: Celes1


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use the desired Node.js version

      - name: Install Dependencies
        run: npm install

     
      - name: Run JMeter Tests
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: ./CSVSample.jmx

      
      - name: Run Selenium test
        run: node selenium.cjs  

      - name: Test using Jest
        run: npm test
    
 
