name: UML Diagram Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Generate UML diagram
      run: npm run generate-uml

    - name: Commit and push UML diagram
      run: |
        git config --global user.email "github@example.com"
        git config --global user.name "GitHub Actions"
        git add .umldiagram.json
        git commit -m "Add UML diagram"
        git push
